# Generated by Django 5.0.3 on 2024-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_usuario', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('contraseña_hash', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=16, null=True)),
                ('otp_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
