# Generated by Django 5.0.3 on 2024-05-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0002_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
