# Generated by Django 5.0.3 on 2024-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0003_delete_ejemplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosgenerales',
            name='telefono',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
