# Generated by Django 5.0.3 on 2024-05-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0004_alter_usuariosgenerales_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosgenerales',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
