# Generated by Django 5.0.3 on 2024-05-16 04:49

import django.utils.timezone
import utaller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0005_alter_usuariosgenerales_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_articulo', models.TextField(max_length=100)),
                ('categoria', models.CharField(choices=[('refacciones', 'Refacciones'), ('herramientas', 'Herramientas'), ('aceites', 'Aceites'), ('filtros', 'Filtros'), ('llantas', 'Llantas'), ('combustible', 'Combustible')], max_length=20)),
                ('unidad_de_medida', models.CharField(choices=[('pieza', 'Pieza'), ('metro', 'Metro'), ('gramo', 'Gramo'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('refacciones', 'Refacciones'), ('herramientas', 'Herramientas'), ('aceites', 'Aceites'), ('filtros', 'Filtros'), ('llantas', 'Llantas'), ('combustible', 'Combustible')], max_length=20)),
                ('unidad_de_medida', models.CharField(choices=[('pieza', 'Pieza'), ('metro', 'Metro'), ('gramo', 'Gramo'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro')], max_length=20)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_articulo', models.TextField(max_length=100)),
                ('entrada_articulo', models.CharField(max_length=100, unique=True, verbose_name=utaller.models.EntradaArticulo)),
                ('numero_orden', models.CharField(max_length=100)),
                ('unidad_de_medida', models.CharField(choices=[('pieza', 'Pieza'), ('metro', 'Metro'), ('gramo', 'Gramo'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro')], max_length=20)),
                ('unidad', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('departamento', models.CharField(choices=[('limpia_pública', 'Limpia_Pública'), ('maquinaria_pesada', 'Maquinaria_Pesada'), ('obras_públicas', 'Obras_Públicas'), ('ornatos', 'Ornatos'), ('policía_municipal', 'Policía_Municipal'), ('presidencia', 'Presidencia'), ('protección_civil', 'Protección_Civil'), ('recursos_humanos', 'Recursos_Humanos'), ('infraestructura_urbana', 'Infraestructura_Urbana'), ('gobierno', 'Gobierno'), ('dirección_de_ingresos', 'Dirección_De_Ingresos'), ('dirección_de_gobernación', 'Dirección_De_Gobernación'), ('dif_municipal', 'Dif_Municipal'), ('desarrollo_urbano_y_medio_ambiente', 'Desarrollo_Urbano_Y_Medio_Ambiente'), ('comunicación_social', 'Comunicación_Social'), ('alumbrado_público', 'Alumbrad_Público'), ('basurero_municipal', 'Basurero_Municipal'), ('atención_y_participación_ciudadana', 'Atención_Y_Participación_Ciudadana'), ('agencia_municipal_de_mundo_nuevo', 'Agencia_Municipal_De_Mundo_Nuevo'), ('acción_social', 'Acción_Social')], max_length=100)),
                ('fecha_y_hora_salida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
