# Generated by Django 5.0.3 on 2024-05-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0006_entradaarticulo_inventario_salidaarticulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaarticulo',
            name='entrada_articulo',
        ),
    ]
