# Generated by Django 5.0.3 on 2024-05-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0008_alter_salidaarticulo_nombre_de_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaarticulo',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='salidaarticulo',
            name='unidad_de_medida',
        ),
    ]
