# Generated by Django 5.0.3 on 2024-05-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0010_rename_cantidad_disponible_entradaarticulo_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaarticulo',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
    ]
