# Generated by Django 5.0.3 on 2024-05-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0011_rename_cantidad_entradaarticulo_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaarticulo',
            name='nombre_de_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utaller.inventario'),
        ),
    ]
