# Generated by Django 5.0.3 on 2024-05-18 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0012_alter_salidaarticulo_nombre_de_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
