# Generated by Django 5.0.3 on 2024-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0013_inventario_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='nombre_de_articulo',
            field=models.CharField(max_length=100),
        ),
    ]
