# Generated by Django 5.0.3 on 2024-05-23 02:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0014_alter_entradaarticulo_nombre_de_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_y_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_de_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utaller.inventario')),
            ],
        ),
    ]
