# Generated by Django 5.0.3 on 2024-05-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0015_ordensalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensalida',
            name='nombre_de_articulo',
            field=models.CharField(max_length=100),
        ),
    ]
