# Generated by Django 5.0.3 on 2024-05-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0016_alter_ordensalida_nombre_de_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordensalida',
            name='nombre_de_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utaller.inventario'),
        ),
    ]
