# Generated by Django 5.0.3 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0017_alter_ordensalida_nombre_de_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_registro', models.CharField(max_length=100)),
                ('numero_folio', models.CharField(max_length=100)),
                ('concepto', models.TextField()),
                ('fecha_factura', models.DateField()),
                ('archivo', models.FileField(upload_to='facturas/')),
            ],
        ),
    ]
