# Generated by Django 5.0.3 on 2024-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0018_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='clave_registro',
            new_name='clave_de_registro',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fecha_factura',
            new_name='fecha_de_factura',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='numero_folio',
            new_name='numero_de_folio',
        ),
    ]
