# Generated by Django 5.0.3 on 2024-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0020_alter_factura_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaarticulo',
            name='departamento',
            field=models.CharField(choices=[('limpia_pública', 'Limpia Pública'), ('maquinaria_pesada', 'Maquinaria Pesada'), ('obras_públicas', 'Obras Públicas'), ('ornatos', 'Ornatos'), ('policía_municipal', 'Policía Municipal'), ('presidencia', 'Presidencia'), ('protección_civil', 'Protección Civil'), ('recursos_humanos', 'Recursos Humanos'), ('infraestructura_urbana', 'Infraestructura Urbana'), ('gobierno', 'Gobierno'), ('dirección_de_ingresos', 'Dirección De Ingresos'), ('dirección_de_gobernación', 'Dirección De Gobernación'), ('dif_municipal', 'Dif Municipal'), ('desarrollo_urbano_y_medio_ambiente', 'Desarrollo Urbano Y Medio Ambiente'), ('comunicación_social', 'Comunicación Social'), ('alumbrado_público', 'Alumbrado Público'), ('basurero_municipal', 'Basurero Municipal'), ('atención_y_participación_ciudadana', 'Atención Y Participación Ciudadana'), ('agencia_municipal_de_mundo_nuevo', 'Agencia Municipal De Mundo Nuevo'), ('acción_social', 'Acción Social')], max_length=100),
        ),
    ]
