# Generated by Django 5.0.3 on 2024-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0021_alter_salidaarticulo_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulos', models.ManyToManyField(to='utaller.entradaarticulo')),
            ],
        ),
    ]
