# Generated by Django 5.0.3 on 2024-05-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0023_reportes_fecha_creacion_reportes_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportes',
        ),
    ]
