# Generated by Django 5.0.3 on 2024-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utaller', '0024_delete_reportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_de_registro', models.CharField(max_length=100)),
                ('numero_de_folio', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('fecha_de_reportes', models.DateField()),
                ('archivo', models.FileField(upload_to='reportes/')),
            ],
        ),
    ]
